import { Recipe } from "@/type/food";
const recipesData: Recipe[] = [
  {
    id: 1,
    title: "Creamy Garlic Parmesan Pasta",
    description:
      "A rich and creamy pasta dish with garlic, parmesan, and fresh herbs that's perfect for weeknight dinners.",
    image:
      "https://media.cnn.com/api/v1/images/stellar/prod/150813135423-korea-food-map-bibimbap.jpg?q=w_1110,c_fill",
    category: "Italian",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    calories: 485,
    rating: 4.8,
    totalRatings: 234,
    author: {
      id: 101,
      name: "Maria Rodriguez",
      username: "chef_maria",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      verified: true,
      followers: 15420,
    },
    ingredients: [
      { item: "Fettuccine pasta", amount: "1 lb", metric: "450g" },
      { item: "Heavy cream", amount: "1 cup", metric: "240ml" },
      { item: "Parmesan cheese, grated", amount: "1 cup", metric: "100g" },
      { item: "Garlic cloves, minced", amount: "4", metric: "4" },
      { item: "Butter", amount: "3 tbsp", metric: "45g" },
      { item: "Fresh parsley", amount: "1/4 cup", metric: "15g" },
      { item: "Salt and pepper", amount: "to taste", metric: "to taste" },
    ],
    instructions: [
      "Cook pasta according to package directions until al dente. Reserve 1 cup pasta water before draining.",
      "In a large skillet, melt butter over medium heat. Add minced garlic and cook for 1 minute until fragrant.",
      "Pour in heavy cream and bring to a gentle simmer. Cook for 2-3 minutes until slightly thickened.",
      "Add drained pasta to the skillet and toss to combine.",
      "Remove from heat and add parmesan cheese, tossing until melted and creamy.",
      "Add pasta water as needed to achieve desired consistency.",
      "Season with salt, pepper, and garnish with fresh parsley before serving.",
    ],
    tags: ["comfort food", "quick", "creamy", "italian", "pasta"],
    nutritionFacts: {
      calories: 485,
      protein: 18,
      carbs: 52,
      fat: 22,
      fiber: 3,
      sugar: 4,
    },
    reviews: [
      {
        id: 1001,
        user: {
          name: "Sarah Johnson",
          username: "sarahcooks",
          avatar:
            "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50",
        },
        rating: 5,
        comment:
          "Absolutely delicious! Made this for date night and it was perfect. The garlic flavor is amazing.",
        date: "2024-01-15",
        helpful: 23,
      },
      {
        id: 1002,
        user: {
          name: "Mike Chen",
          username: "mikeeats",
          avatar:
            "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50",
        },
        rating: 4,
        comment:
          "Great recipe! I added some grilled chicken to make it more filling. Kids loved it too.",
        date: "2024-01-20",
        helpful: 15,
      },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-25",
  },
  {
    id: 2,
    title: "Spicy Korean BBQ Beef Bowl",
    description:
      "Tender marinated beef with spicy gochujang sauce served over rice with fresh vegetables.",
    image: "https://tiffycooks.com/wp-content/uploads/2020/10/beef-bowl-.png",
    category: "Korean",
    difficulty: "Medium",
    prepTime: 45,
    cookTime: 15,
    totalTime: 60,
    servings: 2,
    calories: 620,
    rating: 4.6,
    totalRatings: 189,
    author: {
      id: 102,
      name: "James Kim",
      username: "kimchi_king",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      verified: true,
      followers: 28500,
    },
    ingredients: [
      { item: "Beef ribeye, thinly sliced", amount: "1 lb", metric: "450g" },
      { item: "Jasmine rice", amount: "1 cup", metric: "200g" },
      { item: "Gochujang paste", amount: "3 tbsp", metric: "45ml" },
      { item: "Soy sauce", amount: "1/4 cup", metric: "60ml" },
      { item: "Brown sugar", amount: "2 tbsp", metric: "30g" },
      { item: "Sesame oil", amount: "2 tbsp", metric: "30ml" },
      { item: "Garlic, minced", amount: "4 cloves", metric: "4 cloves" },
      { item: "Fresh ginger, grated", amount: "1 tbsp", metric: "15g" },
      { item: "Cucumber, julienned", amount: "1", metric: "1" },
      { item: "Carrots, julienned", amount: "2", metric: "2" },
      { item: "Green onions", amount: "3", metric: "3" },
      { item: "Sesame seeds", amount: "1 tbsp", metric: "15g" },
    ],
    instructions: [
      "Cook jasmine rice according to package instructions and keep warm.",
      "In a bowl, whisk together gochujang, soy sauce, brown sugar, sesame oil, garlic, and ginger for marinade.",
      "Marinate sliced beef in half the sauce mixture for 30 minutes.",
      "Heat a large skillet or wok over high heat. Cook marinated beef for 3-4 minutes until caramelized.",
      "Prepare fresh vegetables while beef cooks.",
      "Serve beef over rice, topped with fresh vegetables and remaining sauce.",
      "Garnish with green onions and sesame seeds.",
    ],
    tags: ["korean", "spicy", "beef", "rice bowl", "asian fusion"],
    nutritionFacts: {
      calories: 620,
      protein: 35,
      carbs: 58,
      fat: 28,
      fiber: 4,
      sugar: 12,
    },
    reviews: [
      {
        id: 2001,
        user: {
          name: "Lisa Park",
          username: "foodie_lisa",
          avatar:
            "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=50",
        },
        rating: 5,
        comment:
          "This is restaurant quality! The marinade is incredible and the spice level is perfect.",
        date: "2024-02-01",
        helpful: 31,
      },
      {
        id: 2002,
        user: {
          name: "David Martinez",
          username: "spice_lover",
          avatar:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50",
        },
        rating: 4,
        comment:
          "Love the heat! I doubled the gochujang because I like it extra spicy. Will definitely make again.",
        date: "2024-02-05",
        helpful: 18,
      },
    ],
    createdAt: "2024-01-28",
    updatedAt: "2024-02-10",
  },
  {
    id: 1,
    title: "Creamy Garlic Parmesan Pasta",
    description:
      "A rich and creamy pasta dish with garlic, parmesan, and fresh herbs that's perfect for weeknight dinners.",
    image:
      "https://media.cnn.com/api/v1/images/stellar/prod/150813135423-korea-food-map-bibimbap.jpg?q=w_1110,c_fill",
    category: "Italian",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    calories: 485,
    rating: 4.8,
    totalRatings: 234,
    author: {
      id: 101,
      name: "Maria Rodriguez",
      username: "chef_maria",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      verified: true,
      followers: 15420,
    },
    ingredients: [
      { item: "Fettuccine pasta", amount: "1 lb", metric: "450g" },
      { item: "Heavy cream", amount: "1 cup", metric: "240ml" },
      { item: "Parmesan cheese, grated", amount: "1 cup", metric: "100g" },
      { item: "Garlic cloves, minced", amount: "4", metric: "4" },
      { item: "Butter", amount: "3 tbsp", metric: "45g" },
      { item: "Fresh parsley", amount: "1/4 cup", metric: "15g" },
      { item: "Salt and pepper", amount: "to taste", metric: "to taste" },
    ],
    instructions: [
      "Cook pasta according to package directions until al dente. Reserve 1 cup pasta water before draining.",
      "In a large skillet, melt butter over medium heat. Add minced garlic and cook for 1 minute until fragrant.",
      "Pour in heavy cream and bring to a gentle simmer. Cook for 2-3 minutes until slightly thickened.",
      "Add drained pasta to the skillet and toss to combine.",
      "Remove from heat and add parmesan cheese, tossing until melted and creamy.",
      "Add pasta water as needed to achieve desired consistency.",
      "Season with salt, pepper, and garnish with fresh parsley before serving.",
    ],
    tags: ["comfort food", "quick", "creamy", "italian", "pasta"],
    nutritionFacts: {
      calories: 485,
      protein: 18,
      carbs: 52,
      fat: 22,
      fiber: 3,
      sugar: 4,
    },
    reviews: [
      {
        id: 1001,
        user: {
          name: "Sarah Johnson",
          username: "sarahcooks",
          avatar:
            "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50",
        },
        rating: 5,
        comment:
          "Absolutely delicious! Made this for date night and it was perfect. The garlic flavor is amazing.",
        date: "2024-01-15",
        helpful: 23,
      },
      {
        id: 1002,
        user: {
          name: "Mike Chen",
          username: "mikeeats",
          avatar:
            "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50",
        },
        rating: 4,
        comment:
          "Great recipe! I added some grilled chicken to make it more filling. Kids loved it too.",
        date: "2024-01-20",
        helpful: 15,
      },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-25",
  },
  {
    id: 2,
    title: "Spicy Korean BBQ Beef Bowl",
    description:
      "Tender marinated beef with spicy gochujang sauce served over rice with fresh vegetables.",
    image: "https://tiffycooks.com/wp-content/uploads/2020/10/beef-bowl-.png",
    category: "Korean",
    difficulty: "Medium",
    prepTime: 45,
    cookTime: 15,
    totalTime: 60,
    servings: 2,
    calories: 620,
    rating: 4.6,
    totalRatings: 189,
    author: {
      id: 102,
      name: "James Kim",
      username: "kimchi_king",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      verified: true,
      followers: 28500,
    },
    ingredients: [
      { item: "Beef ribeye, thinly sliced", amount: "1 lb", metric: "450g" },
      { item: "Jasmine rice", amount: "1 cup", metric: "200g" },
      { item: "Gochujang paste", amount: "3 tbsp", metric: "45ml" },
      { item: "Soy sauce", amount: "1/4 cup", metric: "60ml" },
      { item: "Brown sugar", amount: "2 tbsp", metric: "30g" },
      { item: "Sesame oil", amount: "2 tbsp", metric: "30ml" },
      { item: "Garlic, minced", amount: "4 cloves", metric: "4 cloves" },
      { item: "Fresh ginger, grated", amount: "1 tbsp", metric: "15g" },
      { item: "Cucumber, julienned", amount: "1", metric: "1" },
      { item: "Carrots, julienned", amount: "2", metric: "2" },
      { item: "Green onions", amount: "3", metric: "3" },
      { item: "Sesame seeds", amount: "1 tbsp", metric: "15g" },
    ],
    instructions: [
      "Cook jasmine rice according to package instructions and keep warm.",
      "In a bowl, whisk together gochujang, soy sauce, brown sugar, sesame oil, garlic, and ginger for marinade.",
      "Marinate sliced beef in half the sauce mixture for 30 minutes.",
      "Heat a large skillet or wok over high heat. Cook marinated beef for 3-4 minutes until caramelized.",
      "Prepare fresh vegetables while beef cooks.",
      "Serve beef over rice, topped with fresh vegetables and remaining sauce.",
      "Garnish with green onions and sesame seeds.",
    ],
    tags: ["korean", "spicy", "beef", "rice bowl", "asian fusion"],
    nutritionFacts: {
      calories: 620,
      protein: 35,
      carbs: 58,
      fat: 28,
      fiber: 4,
      sugar: 12,
    },
    reviews: [
      {
        id: 2001,
        user: {
          name: "Lisa Park",
          username: "foodie_lisa",
          avatar:
            "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=50",
        },
        rating: 5,
        comment:
          "This is restaurant quality! The marinade is incredible and the spice level is perfect.",
        date: "2024-02-01",
        helpful: 31,
      },
      {
        id: 2002,
        user: {
          name: "David Martinez",
          username: "spice_lover",
          avatar:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50",
        },
        rating: 4,
        comment:
          "Love the heat! I doubled the gochujang because I like it extra spicy. Will definitely make again.",
        date: "2024-02-05",
        helpful: 18,
      },
    ],
    createdAt: "2024-01-28",
    updatedAt: "2024-02-10",
  },
  {
    id: 1,
    title: "Creamy Garlic Parmesan Pasta",
    description:
      "A rich and creamy pasta dish with garlic, parmesan, and fresh herbs that's perfect for weeknight dinners.",
    image:
      "https://media.cnn.com/api/v1/images/stellar/prod/150813135423-korea-food-map-bibimbap.jpg?q=w_1110,c_fill",
    category: "Italian",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    calories: 485,
    rating: 4.8,
    totalRatings: 234,
    author: {
      id: 101,
      name: "Maria Rodriguez",
      username: "chef_maria",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      verified: true,
      followers: 15420,
    },
    ingredients: [
      { item: "Fettuccine pasta", amount: "1 lb", metric: "450g" },
      { item: "Heavy cream", amount: "1 cup", metric: "240ml" },
      { item: "Parmesan cheese, grated", amount: "1 cup", metric: "100g" },
      { item: "Garlic cloves, minced", amount: "4", metric: "4" },
      { item: "Butter", amount: "3 tbsp", metric: "45g" },
      { item: "Fresh parsley", amount: "1/4 cup", metric: "15g" },
      { item: "Salt and pepper", amount: "to taste", metric: "to taste" },
    ],
    instructions: [
      "Cook pasta according to package directions until al dente. Reserve 1 cup pasta water before draining.",
      "In a large skillet, melt butter over medium heat. Add minced garlic and cook for 1 minute until fragrant.",
      "Pour in heavy cream and bring to a gentle simmer. Cook for 2-3 minutes until slightly thickened.",
      "Add drained pasta to the skillet and toss to combine.",
      "Remove from heat and add parmesan cheese, tossing until melted and creamy.",
      "Add pasta water as needed to achieve desired consistency.",
      "Season with salt, pepper, and garnish with fresh parsley before serving.",
    ],
    tags: ["comfort food", "quick", "creamy", "italian", "pasta"],
    nutritionFacts: {
      calories: 485,
      protein: 18,
      carbs: 52,
      fat: 22,
      fiber: 3,
      sugar: 4,
    },
    reviews: [
      {
        id: 1001,
        user: {
          name: "Sarah Johnson",
          username: "sarahcooks",
          avatar:
            "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50",
        },
        rating: 5,
        comment:
          "Absolutely delicious! Made this for date night and it was perfect. The garlic flavor is amazing.",
        date: "2024-01-15",
        helpful: 23,
      },
      {
        id: 1002,
        user: {
          name: "Mike Chen",
          username: "mikeeats",
          avatar:
            "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50",
        },
        rating: 4,
        comment:
          "Great recipe! I added some grilled chicken to make it more filling. Kids loved it too.",
        date: "2024-01-20",
        helpful: 15,
      },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-25",
  },
  {
    id: 2,
    title: "Spicy Korean BBQ Beef Bowl",
    description:
      "Tender marinated beef with spicy gochujang sauce served over rice with fresh vegetables.",
    image: "https://tiffycooks.com/wp-content/uploads/2020/10/beef-bowl-.png",
    category: "Korean",
    difficulty: "Medium",
    prepTime: 45,
    cookTime: 15,
    totalTime: 60,
    servings: 2,
    calories: 620,
    rating: 4.6,
    totalRatings: 189,
    author: {
      id: 102,
      name: "James Kim",
      username: "kimchi_king",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      verified: true,
      followers: 28500,
    },
    ingredients: [
      { item: "Beef ribeye, thinly sliced", amount: "1 lb", metric: "450g" },
      { item: "Jasmine rice", amount: "1 cup", metric: "200g" },
      { item: "Gochujang paste", amount: "3 tbsp", metric: "45ml" },
      { item: "Soy sauce", amount: "1/4 cup", metric: "60ml" },
      { item: "Brown sugar", amount: "2 tbsp", metric: "30g" },
      { item: "Sesame oil", amount: "2 tbsp", metric: "30ml" },
      { item: "Garlic, minced", amount: "4 cloves", metric: "4 cloves" },
      { item: "Fresh ginger, grated", amount: "1 tbsp", metric: "15g" },
      { item: "Cucumber, julienned", amount: "1", metric: "1" },
      { item: "Carrots, julienned", amount: "2", metric: "2" },
      { item: "Green onions", amount: "3", metric: "3" },
      { item: "Sesame seeds", amount: "1 tbsp", metric: "15g" },
    ],
    instructions: [
      "Cook jasmine rice according to package instructions and keep warm.",
      "In a bowl, whisk together gochujang, soy sauce, brown sugar, sesame oil, garlic, and ginger for marinade.",
      "Marinate sliced beef in half the sauce mixture for 30 minutes.",
      "Heat a large skillet or wok over high heat. Cook marinated beef for 3-4 minutes until caramelized.",
      "Prepare fresh vegetables while beef cooks.",
      "Serve beef over rice, topped with fresh vegetables and remaining sauce.",
      "Garnish with green onions and sesame seeds.",
    ],
    tags: ["korean", "spicy", "beef", "rice bowl", "asian fusion"],
    nutritionFacts: {
      calories: 620,
      protein: 35,
      carbs: 58,
      fat: 28,
      fiber: 4,
      sugar: 12,
    },
    reviews: [
      {
        id: 2001,
        user: {
          name: "Lisa Park",
          username: "foodie_lisa",
          avatar:
            "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=50",
        },
        rating: 5,
        comment:
          "This is restaurant quality! The marinade is incredible and the spice level is perfect.",
        date: "2024-02-01",
        helpful: 31,
      },
      {
        id: 2002,
        user: {
          name: "David Martinez",
          username: "spice_lover",
          avatar:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50",
        },
        rating: 4,
        comment:
          "Love the heat! I doubled the gochujang because I like it extra spicy. Will definitely make again.",
        date: "2024-02-05",
        helpful: 18,
      },
    ],
    createdAt: "2024-01-28",
    updatedAt: "2024-02-10",
  },
  {
    id: 1,
    title: "Creamy Garlic Parmesan Pasta",
    description:
      "A rich and creamy pasta dish with garlic, parmesan, and fresh herbs that's perfect for weeknight dinners.",
    image:
      "https://media.cnn.com/api/v1/images/stellar/prod/150813135423-korea-food-map-bibimbap.jpg?q=w_1110,c_fill",
    category: "Italian",
    difficulty: "Easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    calories: 485,
    rating: 4.8,
    totalRatings: 234,
    author: {
      id: 101,
      name: "Maria Rodriguez",
      username: "chef_maria",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      verified: true,
      followers: 15420,
    },
    ingredients: [
      { item: "Fettuccine pasta", amount: "1 lb", metric: "450g" },
      { item: "Heavy cream", amount: "1 cup", metric: "240ml" },
      { item: "Parmesan cheese, grated", amount: "1 cup", metric: "100g" },
      { item: "Garlic cloves, minced", amount: "4", metric: "4" },
      { item: "Butter", amount: "3 tbsp", metric: "45g" },
      { item: "Fresh parsley", amount: "1/4 cup", metric: "15g" },
      { item: "Salt and pepper", amount: "to taste", metric: "to taste" },
    ],
    instructions: [
      "Cook pasta according to package directions until al dente. Reserve 1 cup pasta water before draining.",
      "In a large skillet, melt butter over medium heat. Add minced garlic and cook for 1 minute until fragrant.",
      "Pour in heavy cream and bring to a gentle simmer. Cook for 2-3 minutes until slightly thickened.",
      "Add drained pasta to the skillet and toss to combine.",
      "Remove from heat and add parmesan cheese, tossing until melted and creamy.",
      "Add pasta water as needed to achieve desired consistency.",
      "Season with salt, pepper, and garnish with fresh parsley before serving.",
    ],
    tags: ["comfort food", "quick", "creamy", "italian", "pasta"],
    nutritionFacts: {
      calories: 485,
      protein: 18,
      carbs: 52,
      fat: 22,
      fiber: 3,
      sugar: 4,
    },
    reviews: [
      {
        id: 1001,
        user: {
          name: "Sarah Johnson",
          username: "sarahcooks",
          avatar:
            "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50",
        },
        rating: 5,
        comment:
          "Absolutely delicious! Made this for date night and it was perfect. The garlic flavor is amazing.",
        date: "2024-01-15",
        helpful: 23,
      },
      {
        id: 1002,
        user: {
          name: "Mike Chen",
          username: "mikeeats",
          avatar:
            "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50",
        },
        rating: 4,
        comment:
          "Great recipe! I added some grilled chicken to make it more filling. Kids loved it too.",
        date: "2024-01-20",
        helpful: 15,
      },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-25",
  },
  {
    id: 2,
    title: "Spicy Korean BBQ Beef Bowl",
    description:
      "Tender marinated beef with spicy gochujang sauce served over rice with fresh vegetables.",
    image: "https://tiffycooks.com/wp-content/uploads/2020/10/beef-bowl-.png",
    category: "Korean",
    difficulty: "Medium",
    prepTime: 45,
    cookTime: 15,
    totalTime: 60,
    servings: 2,
    calories: 620,
    rating: 4.6,
    totalRatings: 189,
    author: {
      id: 102,
      name: "James Kim",
      username: "kimchi_king",
      avatar:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
      verified: true,
      followers: 28500,
    },
    ingredients: [
      { item: "Beef ribeye, thinly sliced", amount: "1 lb", metric: "450g" },
      { item: "Jasmine rice", amount: "1 cup", metric: "200g" },
      { item: "Gochujang paste", amount: "3 tbsp", metric: "45ml" },
      { item: "Soy sauce", amount: "1/4 cup", metric: "60ml" },
      { item: "Brown sugar", amount: "2 tbsp", metric: "30g" },
      { item: "Sesame oil", amount: "2 tbsp", metric: "30ml" },
      { item: "Garlic, minced", amount: "4 cloves", metric: "4 cloves" },
      { item: "Fresh ginger, grated", amount: "1 tbsp", metric: "15g" },
      { item: "Cucumber, julienned", amount: "1", metric: "1" },
      { item: "Carrots, julienned", amount: "2", metric: "2" },
      { item: "Green onions", amount: "3", metric: "3" },
      { item: "Sesame seeds", amount: "1 tbsp", metric: "15g" },
    ],
    instructions: [
      "Cook jasmine rice according to package instructions and keep warm.",
      "In a bowl, whisk together gochujang, soy sauce, brown sugar, sesame oil, garlic, and ginger for marinade.",
      "Marinate sliced beef in half the sauce mixture for 30 minutes.",
      "Heat a large skillet or wok over high heat. Cook marinated beef for 3-4 minutes until caramelized.",
      "Prepare fresh vegetables while beef cooks.",
      "Serve beef over rice, topped with fresh vegetables and remaining sauce.",
      "Garnish with green onions and sesame seeds.",
    ],
    tags: ["korean", "spicy", "beef", "rice bowl", "asian fusion"],
    nutritionFacts: {
      calories: 620,
      protein: 35,
      carbs: 58,
      fat: 28,
      fiber: 4,
      sugar: 12,
    },
    reviews: [
      {
        id: 2001,
        user: {
          name: "Lisa Park",
          username: "foodie_lisa",
          avatar:
            "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=50",
        },
        rating: 5,
        comment:
          "This is restaurant quality! The marinade is incredible and the spice level is perfect.",
        date: "2024-02-01",
        helpful: 31,
      },
      {
        id: 2002,
        user: {
          name: "David Martinez",
          username: "spice_lover",
          avatar:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50",
        },
        rating: 4,
        comment:
          "Love the heat! I doubled the gochujang because I like it extra spicy. Will definitely make again.",
        date: "2024-02-05",
        helpful: 18,
      },
    ],
    createdAt: "2024-01-28",
    updatedAt: "2024-02-10",
  },
];

export default recipesData;
